SYMPOWER-3065 | Expand simple logging listener signature to include raw message format
nemecec/slf4j pull request #5
Opened 2021-09-24 13:10 UTC by tonisojandu-sympower

2021-09-24 20:51 UTC, neeme-sympower requested changes
Suggested some minor changes.

2021-09-24 20:51 UTC, neeme-sympower commented on slf4j-simple/src/main/java/org/slf4j/impl/SimpleLogger.java
> +    private void logImpl(SimpleLogListener listener, long timestamp, int level, String threadName,  String messageFormat, String message,Throwable t) {
```suggestion
    private void logImpl(SimpleLogListener listener, long timestamp, int level, String threadName, String messageFormat, String message, Throwable t) {
```

2021-09-24 20:51 UTC, neeme-sympower commented on slf4j-simple/src/test/java/org/slf4j/impl/SimpleLoggerTest.java
> +        assertArrayListMatches(listener.capturedMessages, MESSAGE_FORMAT.replaceAll("\\{}", PARAMETER));
I personally do not consider such value manipulation to be a good style in unit tests. Better have a constant, a'la:
```java
private static final String EXPECTED_FORMATTED_MESSAGE = "This is a format: " + PARAMETER;
```
And then:
```suggestion
        assertArrayListMatches(listener.capturedMessages, EXPECTED_FORMATTED_MESSAGE);
```

2021-09-27 07:12 UTC, MikeNikolopoulos requested changes
Neeme has covered me.

2021-09-27 09:03 UTC, neeme-sympower approved these changes
One minor comment, can be approved already.

2021-09-27 09:03 UTC, neeme-sympower commented on slf4j-simple/src/test/java/org/slf4j/impl/SimpleLoggerTest.java
> +    private static final String EXPECTED_FORMATTED_MESSAGE = "This is a format: " + PARAMETER;
I would suggest to move this right after `MESSAGE_FORMAT`, so it is more obvious that these two are related.

2021-09-27 10:09 UTC, MikeNikolopoulos approved these changes

2021-09-28 06:58 UTC, merged